### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by VegeBun-csj** [DoraFactory/HBBFT-Node#4]
- [ ] Test RBC and ABA execution time
- [ ] Required: docker-compose improvement(using docker-compose template) which will provide more flexible configuration. 
- [ ] Required: CFT environment
- [ ] Required: BFT environment
